[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "echoe-security"
version = "0.1.0"
description = "Security utilities for echoe-workspace"
requires-python = ">=3.9"
dependencies = [
    "echoe-core",
    "cryptography>=41.0.0",
    "pyjwt>=2.8.0",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["*"]
