tasks:
  - task_id: "docs-sync"
    name: "Sync API Docs"
    module: "automation.tasks.sync_api_docs"
    params:
      output_json: "docs/openapi.json"
      output_md: "docs/API_REFERENCE.md"
    priority: "high"

  - task_id: "smoke"
    name: "Smoke Test Endpoints"
    module: "automation.tasks.smoke_test_endpoints"
    params:
      base_url: null  # use local TestClient when null
    priority: "high"

  - task_id: "deps"
    name: "Update Dependencies"
    module: "automation.tasks.deps_update"
    params:
      apply: false
    priority: "medium"

  - task_id: "sec"
    name: "Security Scan"
    module: "automation.tasks.security_scan"
    params: {}
    priority: "high"

  - task_id: "perf"
    name: "Performance Benchmark"
    module: "automation.tasks.perf_bench"
    params:
      iterations: 5
    priority: "medium"

  - task_id: "release"
    name: "Generate Release Notes"
    module: "automation.tasks.release_notes"
    params:
      since_tag: null
      out_file: "RELEASE_NOTES.md"
    priority: "low"

  - task_id: "sanitize"
    name: "Sanitize Codebase"
    module: "automation.tasks.sanitize_codebase"
    params:
      target_directory: "app"
      rules: ["remove_temp_files", "format_code"]
    priority: "low"

  - task_id: "foreign_deps_guard"
    name: "Foreign Dependency Sanitize"
    module: "automation.tasks.foreign_dependency_sanitize"
    params:
      apply_changes: false
      delete_node_configs: false
      report_file: "automation/reports/foreign_dependency_report.json"
    priority: "high"

  - task_id: "sec_monitor"
    name: "Security Monitoring"
    module: "automation.tasks.security_monitoring"
    params:
      severity_threshold: "HIGH"
      output_file: "automation/reports/security_monitoring_report.json"
    priority: "high"
