# Blacklist: Disallowed technologies, patterns, and directories for this codebase
# These are strictly forbidden and will be flagged by automation

disallowed_languages:
  - javascript
  - nodejs
  - typescript
  - ruby
  - go
  - rust
  - php
  - java
  - kotlin
  - scala
  - c
  - cpp
  - swift
  - objective-c
  - r
  - elixir

disallowed_extensions:
  - .js
  - .jsx
  - .ts
  - .tsx
  - .mjs
  - .cjs
  - .rb
  - .go
  - .rs
  - .php
  - .java
  - .kt
  - .scala
  - .c
  - .cpp
  - .h
  - .hpp
  - .swift
  - .m
  - .r
  - .exs
  - .lock
  - .gem
  - .class
  - .jar
  - .war
  - .ear
  - .dll
  - .so
  - .dylib

disallowed_tools:
  - npm
  - node
  - yarn
  - pnpm
  - deno
  - bun
  - gem
  - bundle
  - cargo
  - rustc
  - go
  - javac
  - java
  - gradle
  - maven
  - composer
  - mix
  - swift
  - r
  - ruby

blacklist_patterns:
  - "npm install"
  - "node_modules"
  - "yarn install"
  - "pnpm install"
  - "require('"
  - "import * as "
  - "package.json"
  - "Gemfile"
  - "Cargo.toml"
  - "go.mod"
  - "composer.json"
  - "build.gradle"
  - "pom.xml"
  - "mix.exs"
  - "Makefile with non-python targets"

# Any detection of these will trigger a CRITICAL violation
