# Whitelist: Allowed technologies, patterns, and directories for this codebase
# Only these are considered safe and compliant for core and automation

allowed_languages:
  - python
  - bash    # Only for dev/test automation scripts
  - powershell # Only for dev/test automation scripts

allowed_extensions:
  - .py
  - .sh     # Only in scripts/ and root
  - .ps1    # Only in scripts/ and root
  - .md
  - .yml
  - .yaml
  - .json
  - .toml
  - .ini
  - .txt

allowed_directories:
  - app/
  - automation/
  - packages/
  - tests/
  - docs/
  - scripts/
  - config/

allowed_tools:
  - bandit
  - safety
  - black
  - flake8
  - mypy
  - pytest
  - pymarkdownlnt
  - pre-commit

allow_patterns:
  - "python -m automation.scripts.run_automation"
  - "pytest"
  - "bandit"
  - "safety"
  - "pymarkdown scan"

# Anything not listed here will be flagged by automation as a violation
