version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - '8000:8000'
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - ENVIRONMENT=development
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.venv
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Production mode (uncomment to use)
  # api-prod:
  #   build: .
  #   ports:
  #     - '9000:8000'
  #   environment:
  #     - HOST=0.0.0.0
  #     - PORT=8000
  #     - ENVIRONMENT=production
  #   command: python app/main_production.py
  #   restart: unless-stopped
