# Consolidation manifest for scripts and transient files
archive_dir: scripts/archive
modes:
  # default action is to archive; deletion is a separate explicit step
  default: archive

powershell:
  setup:
    survivor: scripts/setup_environment.ps1
    candidates:
      - scripts/setup_dev_env.ps1
      - scripts/setup_dev_env_corrected.ps1
      - scripts/quick_framework_setup.ps1
  security:
    survivor: scripts/weekly-security-check.ps1
    candidates:
      - scripts/monthly-security-audit.ps1
      - scripts/security-scan-python-dependencies.ps1
  emergency:
    survivor: scripts/emergency-lockdown.ps1
    candidates: []
  docker:
    survivor: scripts/docker-dev.ps1
    candidates:
      - scripts/cleanup-vulnerable-images.ps1
  maintenance:
    survivor: scripts/full_sanitization.ps1
    candidates:
      - scripts/cleanup_backups.ps1
      - scripts/validate_environment.ps1
  installer:
    survivor: scripts/framework_installer.ps1
    candidates:
      - scripts/install-secure-storage-provisioner.ps1
  openapi:
    survivor: 42crunch-setup.ps1
    candidates:
      - fix-openapi-security.ps1
      - fix-openapi-simple.ps1
  pr:
    survivor: scripts/create_high_risk_prs.ps1
    candidates:
      - automation/scripts/create_highrisk_prs.ps1
  shortcuts:
    survivor: scripts/quick-launch.ps1
    candidates:
      - make.ps1
      - integration-executor.ps1

bash:
  docker:
    survivor: scripts/docker-dev.sh
    candidates:
      - scripts/docker-security-automation.sh
  ci:
    survivor: scripts/local_ci_simulate.sh
    candidates:
      - scripts/run_tests.sh
      - test_api.sh
  security:
    survivor: scripts/create-security-scripts.sh
    candidates: []

reports:
  bandit:
    survivor: automation/reports/bandit_scan.json
    candidates:
      - bandit_latest.json
      - bandit_report.json
      - bandit-report.json
  security_monitoring:
    survivor: automation/reports/security_monitoring_report.json
    candidates:
      - security_monitoring_report.json
      - app/domains/arts/investlab/security_monitoring_report.json

python:
  security_monitoring:
    survivor: scripts/security_monitoring_final.py
    candidates:
      - scripts/security_monitoring.py
      - scripts/security_monitoring_fixed.py
      - automation/scripts/security_monitor.py
      - automation/security_monitor.py
  main_entry:
    survivor: scripts/main_complete.py
    candidates:
      - scripts/main_working.py
  ci_simulation:
    survivor: scripts/local_ci_simulate.py
    candidates:
      - scripts/simple_review.py
  deploy:
    survivor: Q4/automation/deploy.py
    candidates:
      - scripts/deploy.py
  test_coverage:
    survivor: automation/check_test_coverage.py
    candidates:
      - Q4/automation/check_test_coverage.py
  temp_files:
    survivor: null
    candidates:
      - temp_tour.py
      - validate_security_fixes.py

excel:
  roadmap:
    survivor: Q4/roadmap_export_updated.xlsx
    candidates:
      - roadmap_export_updated.xlsx

text_files:
  security_reports:
    survivor: null
    candidates:
      - security_report_.txt
      - security_report_20251005.txt
      - security_report_20251005_145523.txt
      - docker-security-completion.txt
  logs:
    survivor: null
    candidates:
      - log
  large_files:
    survivor: null
    candidates:
      - exxtended.txt
      - final_plan.txt

json_files:
  security_reports:
    survivor: automation/reports/security-audit-report.json
    candidates:
      - security-audit-report.json
      - security_validation.json
  misc:
    survivor: null
    candidates:
      - openapi-spec.json
      - openapi_response.json
      - phase2_demo_report.json
      - queensgambit_insights.json

cleanup:
  delete_patterns:
    - "**/__pycache__/**"
    - "**/*.pyc"
    - "**/*.pyo"
    - "**/*.tmp"
    - "**/*.temp"
    - "**/*.bak"
    - "scripts/archive/bandit*.json"
  preserve_paths:
    - automation/reports/**
    - docs/**
    - configs/**
    - venv/**
    - .git/**
    - Q4/venv/**
