name: ML Security Enforcement

on:
  push:
    paths:
      - 'requirements*.txt'
      - 'setup.py'
      - 'pyproject.toml'
  pull_request:
    paths:
      - 'requirements*.txt'
      - 'setup.py'
      - 'pyproject.toml'
  workflow_dispatch:
  schedule:
    # Weekly security audits on Mondays at 10:00 UTC
    - cron: '0 10 * * 1'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          pip --version

      - name: Set up pip cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-security.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install security tools
        run: |
          pip install -r requirements-security.txt

      - name: Run pip-audit (SARIF)
        run: |
          pip-audit --requirement requirements.txt --format sarif -o pip-audit-results.sarif

      - name: Generate SBOM
        run: |
          mkdir -p sbom
          cyclonedx-py requirements -r requirements.txt -o sbom/cyclonedx-sbom.xml

      - name: Run Safety (text report)
        run: |
          safety check --full-report -r requirements.txt > safety-report.txt || true

      - name: Verify Egress Policy and Produce Summary
        env:
          CI: true
        run: |
          python -m core_modules.network.policy --verify --summary-out egress-summary.json || true

      - name: Check for high/critical vulnerabilities
        run: |
          # Count vulnerabilities by severity
          HIGH_VULNS=$(python -c "
import json
try:
    with open('pip-audit-results.sarif', 'r') as f:
        data = json.load(f)
    high_count = sum(1 for run in data.get('runs', [])
                    for result in run.get('results', [])
                    if result.get('level') == 'error')
    print(high_count)
except:
    print(0)
")
          if [ "$HIGH_VULNS" -gt 0 ]; then
            echo "::error::Found $HIGH_VULNS high severity vulnerabilities"
            echo "Check the pip-audit-results.sarif artifact for details"
            # Exit with error unless waived
            if [ "${{ github.event_name }}" != "schedule" ]; then
              exit 1
            fi
          fi

      - name: Create security issue for scheduled audit findings
        if: github.event_name == 'schedule' && failure()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            try {
              const safetyReport = fs.readFileSync('safety-report.txt', 'utf8');
              const title = `Scheduled Security Audit - ${new Date().toISOString().split('T')[0]}`;
              const body = `## Automated Security Audit Results\n\n${safetyReport}\n\n**Action Required:**\n- Review and address high/critical vulnerabilities\n- Update dependencies or apply security patches\n- Consider adding security-waiver label if exception is needed\n\nThis issue was created automatically by the scheduled security workflow.`;

              github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: body,
                labels: ['security', 'scheduled-audit', 'dependencies']
              });
            } catch (error) {
              console.log('Could not create issue:', error.message);
            }

      - name: Run Bandit (non-blocking)
        run: |
          bandit -r app core_modules api -c bandit.yaml -f json -o bandit-report.json || echo "Bandit scan completed with findings (non-blocking)"

      - name: Upload security artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-artifacts
          path: |
            pip-audit-results.sarif
            sbom/cyclonedx-sbom.xml
            safety-report.txt
            egress-summary.json
            bandit-report.json

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: pip-audit-results.sarif
