# Automation Framework Configuration

# Framework version
framework:
  version: "1.0.0"

  # Task definitions
  tasks:
    # Category: System maintenance tasks
    maintenance:
      # Frequency: Daily tasks
      daily:
        - "sample_task"

      # Frequency: Weekly tasks
      weekly: []

      # Frequency: Monthly tasks
      monthly: []

    # Category: Security tasks
    security:
      daily: []
      weekly: []
      monthly: []

    # Category: Data processing tasks
    data:
      daily: []
      weekly: []
      monthly: []

# Task-specific configuration
tasks:
  sample_task:
    # Example configuration for the sample task
    target_dir: "./output"

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "automation.log"  # Set to empty string to disable file logging

# Environment settings
environment:
  # Default environment (can be overridden with ENVIRONMENT env var)
  default: "dev"

  # Environment-specific settings
  dev:
    debug: true

  staging:
    debug: false

  prod:
    debug: false
