name: C# Java probe tests

on:
  push:
    paths:
      - 'csharp/**'
  pull_request:
    paths:
      - 'csharp/**'

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Build runner
        run: |
          dotnet build csharp/language-bundle.csproj --configuration Release
      - name: Create fake java.exe and assert runner exit code 0
        run: |
          mkdir -p fake/bin
          $exe = 'fake\bin\java.exe'
          "@echo off\necho fake java" > $exe
          icacls $exe /grant Everyone:F
          dotnet run --project csharp/language-bundle.csproj --configuration Release; if ($LASTEXITCODE -ne 2) { Write-Host "Expected exit code 2 when no java present"; exit 1 }
          move fake bin
          dotnet run --project csharp/language-bundle.csproj --configuration Release; if ($LASTEXITCODE -eq 2) { Write-Host "Expected java present -> not exit 2"; exit 1 }
      - name: Cleanup
        run: echo Done
