name: integration-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Configure Poetry
        run: poetry config virtualenvs.create true
      - name: Install dependencies
        run: poetry install --with dev
      - name: Run integration test
        run: .\integration_test.ps1
        shell: pwsh
        if: runner.os == 'Windows'
